#!/usr/bin/env ruby

require 'asciidoctor'
require 'asciidoctor/cli/options'
require 'asciidoctor/cli/invoker'

require 'asciidoctor-diagram'

invoker = Asciidoctor::Cli::Invoker.new ARGV
invoker.invoke!
exit invoker.code