+++
date = "2014-12-30T00:00:00+02:00"
title = "Impressum"
tags = []
draft = false
description = "Impressum"
+++
include::globals.adoc[]
== Impressum

*Angaben gemäß § 5 TMG*

Mirko Sertic +
Josefine-Mauser-Straße 66 +
48157 Münster

*Kontakt*

Telefon: 01575-1337193 +
E-Mail: mirko@mirkosertic.de

=== Haftungsausschluss

==== Haftung für Inhalte

Die Inhalte dieser Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der
Inhalte kann ich jedoch keine Gewähr übernehmen. Als Diensteanbieter bin ich gemäß &sect; 7 Abs.1 TMG für eigene Inhalte auf
diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach &sect;&sect; 8 bis 10 TMG bin ich als Diensteanbieter jedoch nicht
verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf
eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach
den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der
Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werde ich
diese Inhalte umgehend entfernen.

==== Haftung für Links

Dieses Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte ich keinen Einfluss habe. Deshalb kann ich
für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige
Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche
Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente
inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar.
Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Links umgehend entfernen.

=== Datenschutzerklärung für die Nutzung von Matomo
Ich nutze auf dieser Website Matomo (ehemals Piwik), eine Open-Source-Software zur statistischen Auswertung der Besucherzugriffe.
Matomo verwendet sogenannte "Cookies", Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung
der Website durch Sie ermöglichen.

==== Art und Umfang der Datenverarbeitung
Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden auf einem Server in Deutschland gespeichert.
Die IP-Adresse wird sofort nach der Verarbeitung und vor deren Speicherung anonymisiert. Sie können die Installation der
Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern.
Matomo ist so konfiguriert, dass:

* Ihre IP-Adresse vor der Speicherung anonymisiert wird
* keine personenbezogenen Daten gespeichert werden
* Cookies nur mit Ihrer Einwilligung gesetzt werden
* die Daten nicht an Dritte weitergegeben werden
* alle Daten ausschließlich auf eigenen Servern in Deutschland verarbeitet werden

==== Zweck der Datenverarbeitung
Die Verarbeitung der Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Das berechtigtes Interesse liegt in
der Optimierung dieser Website und der Verbesserung dieses Angebots. Die statistische Analyse des Nutzerverhaltens
erfolgt ausschließlich zu Optimierungszwecken dieser Website.

==== Ihre Rechte
Sie können der Datenverarbeitung widersprechen, indem Sie:

* Das unten stehende Opt-out aktivieren
* In Ihrem Browser das "Do Not Track" Feature aktivieren
* Die Cookie-Einstellungen in Ihrem Browser entsprechend anpassen

==== Opt-Out Möglichkeit
Sie können sich hier entscheiden, ob in Ihrem Browser ein eindeutiger Webanalyse-Cookie abgelegt werden darf, um dem
Betreiber der Website die Erfassung und Analyse verschiedener statistischer Daten zu ermöglichen.

++++
<div id="matomo-opt-out"></div>
<script src="https://analytics.mirkosertic.de/index.php?module=CoreAdminHome&action=optOutJS&divId=matomo-opt-out&language=auto&showIntro=1"></script>
++++

==== Datensicherheit
Ich treffe nach Maßgabe des Art. 32 DSGVO unter Berücksichtigung des Stands der Technik, der Implementierungskosten und
der Art, des Umfangs, der Umstände und der Zwecke der Verarbeitung sowie der unterschiedlichen Eintrittswahrscheinlichkeit
und Schwere des Risikos für die Rechte und Freiheiten natürlicher Personen geeignete technische und organisatorische
Maßnahmen, um ein dem Risiko angemessenes Schutzniveau zu gewährleisten.