+++
date = "2018-10-15T00:00:00+02:00"
title = "My personal list of interesting books"
tags = []
draft = false
description = "A list of maybe interesting books related to technology, software engineering and management"
+++
include::globals.adoc[]
== General software engineering & project management

    * The Mythical Man-Month. Essays on Software Engineering. Frederick P. Brooks
    * Requirements-Engineering und -Management: Professionelle, iterative Anforderungsanalyse für die Praxis. Chris Rupp und die SOPHISTEN
    * The Deadline: A Novel About Project Management. Tom DeMarco
    * The Goal: A Process of Ongoing Improvement. Eliyahu M. Goldratt, Jeff Cox
    * Peopleware: Productive Projects and Teams. Tom DeMarco
    * 97 Things Every Programmer Should Know
    * Knigge für Softwarearchitekten. Peter Hruschka
    * Software-Architektur kompakt: – angemessen und zielorientiert. Gernot Starke
    * Technisches Schreiben (nicht nur) für Informatiker. Peter Rechenberg
    * Software Estimation: Demystifying the Black Art. Steve McConnell
    * Clean Code: A Handbook of Agile Software Craftsmanship. Robert C. Martin
    * Specification by Example. How successful teams deliver the right software. Gojko Adzik
    * Infrastructure as Code. Kief Morris
    * Engineering a Compiler. Linda Torczon, Keith Cooper

== (Object-oriented) design

    * Domain-Driven Design Distilled. Vaugn Vernon
    * Domain-Driven Design: Tackling Complexity in the Heart of Software. Eric J. Evans
    * Design Patterns. Elements of Reusable Object-Oriented Software. Erich Gama, Richard Helm, Ralph E. Johnson, John Vlissides
    * Implementing Domain-Driven Design. Vaughn Vernon
    * Die UML-Kurzreferenz 2.3 für die Praxis. Bernd Oestereich
    * ReleaseIt!: Design and Deploy Production-Ready Software. Michael T. Nygard
    * Reactive Messaging Patterns with the Actor Model. Vaughn Vernon
    * Reactive Design Patterns. Roland Kuhn, Jamie Allen, Brian Hanafee

== Technology

    * Real World Java EE Patterns. Rethinking Best Practices. Adam Bien
    * Real World Java EE Night Hacks. Dissecting the Business Tier. Adam Bien
    * Seven Languages in Seven Weeks: A Pragmatic Guide to Learning Programming Languages (Pragmatic Programmers). Bruce A. Tate
    * The Java EE 6 Tutorial 1: Basic Concepts (Java Series)
    * Spring in Action
    * Hibernate in Action: Practical Object/Relational Mapping
    * Lucene in Action
    * Seven Databases in Seven Weeks: A Guide to Modern Databases and the NoSQL Movement. Eric Redmond and Jim R. Wilson
    * Programming In Scala, Second Edition. Martin Odersky, Lex Spoon, Bill Venners
    * DSLs(Domain-specific languages) in Action. Debasish Ghosh
    * Java EE7 Essentials. Arun Gupta
    * Functional Programming in Java: Harnessing the Power of Java 8 Lambda Expressions. Venkat Subramaniam
    * Version Control with Git: Powerful tools and techniques for collaborative software development. Jon Loeliger und Matthew McCullough
    * JavaScript: The Good Parts: Working with the Shallow Grain of JavaScript. Douglas Crockford
    * Effective Java : Third Edition. Joshua Bloch
    * Deep Learning (Adaptive Computation and Machine Learning). Ian Goodfellow, Yoshua Bengio, Aaron Courville
    
== Others

    * QualityLand. Marc-Uwe Kling
    * The Science of Why: Answers to Questions about the World Around Us. Jay Ingram
    * The Back of the Napkin. Solving problems and selling ideas with pictures. Dan Roam
    * Creating Games, Mechanics, Content and Technology. Morgan McGuire, Odest Chadwicke Jenkins
    * Real-Time Rendering, Third Edition. Tomas Akenine-Möller, Eric Haines, Naty Hoffmann
    * Game Coding Complete, Fourth Edition. Mike McShaffry, David Graham
    * Game Engine Black Book: Wolfenstein 3D. Fabien Sanglard
    * What If?: Serious Scientific Answers to Absurd Hypothetical Questions. Randall Munroe.

