+++
date = "2016-01-01T01:43:48+02:00"
title = "About me"
tags = []
draft = false
+++

== Who am I

I provide Software and Support in the field of electronic data processing. As a consultant and software craftsman I have supported a number of major players in projects of all sizes in Germany and Switzerland. My experience as a developer and architect makes informed decisions, sustainable architectures and sound operation of all kinds of software.

== What I can do for you

In addition to modern application development I am concerned with development and modernization of legacy systems. Here I offer support and advice in the field of architecture, change management and modernization.

*Areas of Activity and Industry Experience*
Consulting, Engineering, Administration, Tourism, eCommerce, Telecommunications

*Programming*
J2EE, JEE & SE, Android, Scala, SQL, XML / XSL, HTML / CSS, Javascript and other

*Databases*
Various relational and non-relational Databases, Embedded Databases

*Operating Systems*
Linux / UNIX derivatives, Windows, Android

*Software Development*
Innovative Applications, UI Prototyping, Test-Driven Development, Domain-Driven Design, QA

*Architecture*
Software Development, Architecture, Management and Modernization of “Legacy” Systems

== My Technology Experience

I have worked with following technolgies(excerpt):

Java (Oracle Java Certified), JEE, EJB, Android, Scala, GWT(Google Web Toolkit), JavaScript, HTML5 Polymer, SOA, XML, Spring, GIT, OOA/D/P, Java2D, Java3D, JavaFX 2.0, SWT, JPA, Hibernate, Spring, JSF, AOP(AspectJ), SOAP, WSDL, CruiseControl / Hudson / Jenkins, Maven, PostgreSQL, Domain-Driven Design, NoSQL, Docker,Windows 3.1 to Windows 8, JBoss AS, Tomcat, TomEE, WebLogic WLS, IBM Websphere, Apache Lucene, Apache Solr, Hibernate Search, Bean Validation, JAXB, StAX, TRaX, V-Modell, HERMES(Swiss), XP, SCRUM, Eclipse, JBuilder, Netbeans, IntelliJ, Canoo ULC, JUnit, Mockito, PowerMock, EasyMock, JSFUnit, DBUnit, Apache OJB, Objektpark, Case Tools, Apache CXF, MyFaces, Tomahawk, Richfaces, Primefaces, PrettyFaces, JasperReports, Informix, MDSD, MDA, XSL:FO, OrientDB, Enterprise Architect, WebGL/OpenGL, C / C++, Selenium, XSLT, JDBC, JSP, Subversion, AWT/SwingJSF, SOAP, REST, Hibernate, Oracle PL-SQL, DB2, MS-SQL, MySQL, UML

I aquired the following certificate:

Technical:

    * 2014 Functional Programming Principles in Scala, EPFL Lausanne
    * 2012 Oracle Java Enterprise Edition 5 Enterprise Architect Certified Master
    * 2009 Sun Certified Developer for Java Web Services (SCDJWS)
    * 2007 Sun Certified Enterprise Architect (SCEA)
    * 2004 Sun Certified Web Component Developer for the Java2 Platform (SCWCD)
    * 2003 Sun Certified Programmer for the Java2 Platform (SCJP)

Methodical:

    * 2010 International Project Management Association IPMA Level D
    * 2008 Certified Professional for Requirements Engineering

== Contact me

Don't hesitate to contact me. I am always glad to help and assist you.

Mirko Sertic +
Josefine-Mauser-Str. 66 +
48157 Münster +
Germany +

Mail: mirko@mirkosertic.de +
GitHub : https://github.com/mirkosertic +
Twitter: https://twitter.com/mirkosertic +
Xing: https://www.xing.com/profile/Mirko_Sertic +
LinkedIn: https://de.linkedin.com/in/mirko-sertic-98882397 +
Google+: https://plus.google.com/112732493059943659026 +
