+++
date = "2024-06-06T00:00:00+02:00"
title = "Tools & Goodies"
tags = []
draft = false
description = "A collection of tools and goodies"
+++
include::globals.adoc[]
== Technical stuff

https://backstage.io[Backstage]

An open source framework for building developer portals. Powered by a centralized software catalog, Backstage restores order to your infrastructure and enables your product teams to ship high-quality code quickly — without compromising autonomy.

https://kaitai.io/[Kaitai Struct]

A new way to develop parsers for binary structures.

https://playwright.dev[Playwright]

Playwright enables reliable end-to-end testing for modern web apps.

https://jsoncrack.com/editor[JSON Crack]

Visualize, analyze, and manipulate data with ease, a versatile and powerful tool for data representation and exploration.

https://www.desmos.com/[Desmos]

Desmos is an advanced graphing calculator implemented as a web application and a mobile application written in TypeScript and JavaScript.

https://architecture-antipatterns.tech/[Architecture Antipatterns]

Discover common architecture antipatterns, learn how to avoid them and overcome design pitfalls! Gain valuable insights, practical advice, and real-world examples to build better software architectures and improve existing ones.

https://roca-style.org/[Resource-Oriented Client Architecture]

A collection of simple recommendations for decent Web application frontends.

https://www.plotjuggler.io/[PlotJuggler]

PlotJuggler is a tool to visualize time series that is fast, powerful and intuitive.

https://docs.dependencytrack.org/[Dependency-Track]

Dependency-Track is an intelligent Component Analysis platform that allows organizations to identify and reduce risk in the software supply chain. Dependency-Track takes a unique and highly beneficial approach by leveraging the capabilities of Software Bill of Materials (SBOM). This approach provides capabilities that traditional Software Composition Analysis (SCA) solutions cannot achieve.

https://cyclonedx.org/[OWASP CycloneDX]

OWASP CycloneDX is a lightweight Software Bill of Materials (SBOM) standard designed for use in application security contexts and supply chain component analysis.

Strategic direction and maintenance of the specification is managed by the CycloneDX Core working group, with origins in the OWASP community.

https://helm.sh/[Helm]

Helm is the best way to find, share, and use software built for Kubernetes.

https://kustomize.io/[Kustomize]

Kustomize introduces a template-free way to customize application configuration that simplifies the use of off-the-shelf applications.

https://www.cypress.io/[Cypress]

The web has evolved. Finally, testing has too. Fast, easy and reliable testing for anything that runs in a browser.

https://insomnia.rest/[Insomnia]

Design and debug APIs like a human, not a robot.

https://camunda.com/[Camunda BPMN / DMN]

The Camunda Workflow Engine is the right choice for both (micro-)service orchestration and human task management.

https://github.com/marcotcr/lime[Lime]

Lime: Explaining the predictions of any machine learning classifier.

https://lernajs.io[Lerna]

A tool for managing JavaScript projects with multiple packages.

https://postcss.org[PostCSS]

A tool for transforming CSS with JavaScript.

https://storybook.js.org/[Storybook]

Storybook is an open source tool for developing UI components in isolation for React, Vue, Angular, and more. It makes building stunning UIs organized and efficient.

https://www.testcontainers.org/[Testcontainers]

Testcontainers is a Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases, Selenium web browsers, or anything else that can run in a Docker container.

https://grafana.com/[Grafana]

The open platform for beautiful analytics and monitoring

https://kafka.apache.org/[Apache Kafka]

Kafka is used for building real-time data pipelines and streaming apps. It is horizontally scalable, fault-tolerant, wicked fast, and runs in production in thousands of companies.

https://www.keycloak.org/[Keycloak]

Keycloak is an open source Identity and Access Management solution aimed at modern applications and services. It makes it easy to secure applications and services with little to no code.

https://gohugo.io/[Hugo]

Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again.

http://cbor.io/[The Concise Binary Object Representation ]

The Concise Binary Object Representation (CBOR) is a data format whose design goals include the possibility of extremely small code size, fairly small message size, and extensibility without the need for version negotiation.

http://www.redblobgames.com/[Red Blob Games]

A wonderful resource about computer algorithms involved in game programming.

https://jakearchibald.com/2014/offline-cookbook[Jake Archibald: The offline cookbook]

Jake Archibald writes about offline Web Applications.

http://scs-architecture.org/[scs-architecture.org]

The Self-contained System (SCS) approach is an architecture that focuses on a separation of the functionality into many independent systems, making the complete logical system a collaboration of many smaller software systems. This avoids the problem of large monoliths that grow constantly and eventually become unmaintainable.

https://www.varnish-cache.org/[Varnish HTTP Cache]

Varnish is an HTTP accelerator designed for content-heavy dynamic web sites as well as heavily consumed APIs. In contrast to other web accelerators, such as Squid, which began life as a client-side cache, or Apache and nginx, which are primarily origin servers, Varnish was designed as an HTTP accelerator. Varnish is focused exclusively on HTTP, unlike other proxy servers that often support FTP, SMTP and other network protocols.

http://hazelcast.org/[Hazelcast IMDG]

The Leading Open Source In-Memory Data Grid: Distributed Computing, Simplified.

http://asciidoctor.org/[Asciidoctor]

Asciidoctor is a fast text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.

http://sqlfiddle.com/[SQL Fiddle]

SQLFiddle is a tool to quickly test sql statements on different databases such as MySQL, PostgreSQL or MSSQL.

http://pitest.org/[Pitest : Real world mutation testing]

PIT is a state of the art mutation testing system, providing gold standard test coverage for Java and the jvm. Its fast, scalable and integrates with modern test and build tooling.

http://infinitest.github.io/[infinitest]

Infinitest is a Continuous Testing plugin for Eclipse and IntelliJ. Each time a change is made on the source code, Infinitest runs all the tests that might fail because of these changes.

https://www.marmoset.co/hexels/[Hexels]

Hexels is a brand new, grid-based art program for Mac and PC that lets you paint with shapes.

http://www.gnu.org/software/octave[GNU Octave]

GNU Octave is a high-level interpreted language, primarily intended for numerical computations. It provides capabilities for the numerical solution of linear and nonlinear problems, and for performing other numerical experiments. It also provides extensive graphics capabilities for data visualization and manipulation. Octave is normally used through its interactive command line interface, but it can also be used to write non-interactive programs. The Octave language is quite similar to Matlab so that most programs are easily portable.

http://www.togglz.org/Togglz[Togglz]

Togglz is an implementation of the http://martinfowler.com/bliki/FeatureToggle.html[Feature Toggle Pattern] for Java. Feature Toggles are a very common agile development practices in the context of continuous deployment and delivery. The basic idea is to associate a toggle with each new feature you are working on. This allows you to enable or disable these features at application runtime, even for individual users.

http://masonry.desandro.com/[Masonry]

Masonry is a JavaScript grid layout library. It works by placing elements in optimal position based on available vertical space, sort of like a mason fitting stones in a wall. You’ve probably seen it in use all over the Internet.

https://github.com/resilience4j/resilience4j[Resilience4j]

Resilience4j is a lightweight, easy-to-use fault tolerance library inspired by
Netflix Hystrix, but designed for Java 8 and functional programming. Lightweight, because the library only uses Vavr, which does not have any other external library dependencies. Netflix Hystrix, in contrast, has a compile dependency to Archaius which has many more external library dependencies such as Guava and Apache Commons Configuration.

http://windup.jboss.org/index.html[JBoss Windup]

JBoss Windup is a tool to simplify JEE application migration from one container to another.

http://addyosmani.com/resources/essentialjsdesignpatterns/book/[Addy Osmani; JavaScript Design Patterns]

An eBook about Design Patterns with JavaScript.

http://stephaneginier.com/sculptgl[Sculpt GL]

A browser based WebGL sculpting tool. Cool!

http://www.oracle.com/technetwork/java/javafx/community/3rd-party-1844355.html[JavaFX Third Party Tools and Utilities]

JavaFX 3rd party tools & utilities.

http://msdn.microsoft.com/en-gb/library/fp160953.aspx[Microsoft JavaScript API for Office]

JavaScript API for Microsoft Office.

http://www.jetbrains.com/idea[IntelliJ IDEA]

IntelliJ IDEA, the one and only IDE you will ever need!

http://modeling-languages.com/[modeling-languages.com]

All you wanted to know about software modeling and model-driven engineering

http://www.gradle.org/[Gradle Build Tool]

Gradle is build automation evolved. Gradle can automate the building, testing, publishing and deployment of software packages.

http://caminao.wordpress.com/[caminao.wordpress.com]

Caminao's way. Do systems know how symbolic they are?

http://www.arc42.de/[arc42: Ressourcen für Softwarearchitekten]

Resources for software developers and architects.

http://arquillian.org/[arquillian.org]

Arquillian is framework to write tests for JEE applications.

http://d3js.org/[D3.js]

D3Js is a JavaScript library for visualisation of data driven documents. It provides some very cool layouts and animation effects.

http://pragprog.com/[The Pragmatic Bookshelf]

The Pragmatic Bookshelf, the source of knowledge

http://en.wikipedia.org/wiki/Edge_Side_Includes[Edge Side Includes]

Edge Side Includes(ESI) is a W3C standard for server side web content integration. ESI is a great alternative to the Java JSR168/268 Portlet specification as it is more lightweight and also supports technologies like CDN(content delivery networks) and true SOA in web applications.

http://mogwai.sourceforge.net/[Project Mogwai]

Mogwai ERDesignerNG is a free Java based entity relationship modeling tool. It is my Open Source Project and hosted on SourceForge.net. I am working on it since 2002.

http://www.balsamiq.com/[Balsamiq mockups]

Using Balsamiq we can create nice looking user interface mockups and storyboards.

http://lesscss.org/[LessCSS]

LessCSS is a tool to generate dynamic CSSon server &amp; client side

http://myfaces.apache.org/extensions/cdi/[MyFaces CODI]

Apache MyFaces CODI provides some very cool extensions for CDI(JSR 299). Check out the slides at http://de.slideshare.net/os890/myfaces-codi-conversations[MyFaces CODI Slides] . CODI and JBoss Seam will become the http://incubator.apache.org/deltaspike/[DeltaSpike] project, which is currently in incubation status.

http://www.querydsl.com/[QueryDSL]

QueryDSL is a framework to create domain specific languages for querying data with JPA, Hibernate, SQL or even Lucene.

http://ocpsoft.org/prettyfaces/[PrettyFaces]

PrettyFaces is a JSF extension creating RESTful URLs or page actions for JSF based applications.

http://juel.sourceforge.net/[JUEL]

Project JUEL offers a high performance implementation of the Java Unified Expression Language. It can be a drop-in replacement for JSF applications to tune their performance.

http://flywaydb.org/[FlywayDB]

Flyway is an agile database migration framework for Java

http://www.liquibase.org/[Liquibase]

Liquibase supports database change management and refactorings.

http://www.eclipse.org/aspectj/[AspectJ]

AspectJ is a leading Aspect Oriented Programing framework.

https://github.com/powermock/powermock/[PowerMock]

PowerMock is a framework extending EasyMock functionalities with other features like mocking of static classes

http://angularjs.org/[Angular]

AngularJS is a toolset for building the framework most suited to your application development(taken from project website).

http://seleniumhq.org/[Selenium]

Selenium is a capture-replay testing tool for browser based applications

http://www.guigarage.com/[Guigarage]

A useful JavaFX ressource

http://www.inf.usi.ch/phd/wettel/codecity.html[CodeCity]

CodeCity is an integrated environment for software analysis, in which software systems are visualized as interactive, navigable 3D cities.

http://www.tomjewett.com/dbdesign/dbdesign.php[Database design with UML and SQL]

A cool summary about database design with UML and SQL.
