name: Build Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: |
          gem install asciidoctor
          gem install coderay
          gem install asciidoctor-kroki
          sudo apt-get install python
          gem install pygments.rb
          which asciidoctor
          which ruby
      - uses: actions/setup-node@v2
        with:
            node-version: '10'
            check-latest: true
      - run: |
          npm install
          npm update
          unset "_JAVA_OPTIONS"
          npm run build
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
          CLEAN: true
      - run: |
          curl http://www.google.com/webmasters/sitemaps/ping?sitemap=https://www.mirkosertic.de/sitemap.xml
          curl http://www.bing.com/ping?sitemap=https://www.mirkosertic.de/sitemap.xml