name: Build Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.160.1'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: |
          gem install coderay
          gem install pygments.rb  -v 3.0.0
          gem install asciidoctor-diagram
          gem install asciidoctor-diagram-ditaamini
          gem install asciidoctor-diagram-plantuml          
          which ruby
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
            check-latest: true
      - run: |
          npm ci
          unset "_JAVA_OPTIONS"
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./public
          clean: true
      - run: |
          curl http://www.google.com/webmasters/sitemaps/ping?sitemap=https://www.mirkosertic.de/sitemap.xml
          curl http://www.bing.com/ping?sitemap=https://www.mirkosertic.de/sitemap.xml
